
import difflib


qa_pairs = {
   
      "hi": "Hello! 😊 Nice to meet you.",
        "hii": "Hello! 👋 How are you?",
        "hello": "Hi there! 🌸",
        "how are you": "I'm just a bot, but I'm doing great! How about you?",
        "i am fine": "Glad to hear that! Keep smiling 😊",
        "i am also fine": "Awesome! Stay positive and take care 🌟",
        "What is your name ": "I am your Student Mental Health Assistant 🤖 ",
        "what can you do": "I can help answer questions about student mental health and support features! Ask me anything.",
        "thank you": "You're welcome! If you have more questions, feel free to ask",
        "thanks": "No problem! I'm here to help anytime 😊",
        "bye": "Goodbye! Take care and stay positive! 👋",
        "ok bye": "Goodbye! Take care and stay positive! 👋",
        "What is your purpose": "My purpose is to assist students with mental health challenges by providing information and support resources.",
        "what is your short  name" : "Call me Just a Friend  😉",
        " can i ask one more question": "Of course! Ask me anything about student mental health and support features.",
        "sure": "Great! What would you like to know?",
        "ok": "Alright! Feel free to ask your question.",
        "good morning": "Good morning! 🌞 Wishing you a productive day ahead.",
        "good afternoon": "Good afternoon! Hope your day is going well.",
        "good evening": "Good evening! 🌆 How are you today?",
        "good night": "Good night! 🌙 Sleep well and take care.",
         "hi": "Hello! 😊 Nice to meet you.",
    "hii": "Hello! 👋 How are you?",
    "hello": "Hi there! 🌸",
    "how are you": "I'm just a bot, but I'm doing great! How about you?",
    "i am fine": "Glad to hear that! Keep smiling 😊",
    "i am also fine": "Awesome! Stay positive and take care 🌟",
    "What is your name ": "I am your Student Mental Health Assistant 🤖",
    "what can you do": "I can help answer questions about student mental health and support features! Ask me anything.",
    "thank you": "You're welcome! If you have more questions, feel free to ask",
    "thanks": "No problem! I'm here to help anytime 😊",
    "bye": "Goodbye! Take care and stay positive! 👋",
    "ok bye": "Goodbye! Take care and stay positive! 👋",
    "What is your purpose": "My purpose is to assist students with mental health challenges by providing information and support resources.",
    "what is your short  name": "Call me Just a Friend 😉",
    "can i ask one more question": "Of course! Ask me anything about student mental health and support features.",
    "sure": "Great! What would you like to know?",
    "ok": "Alright! Feel free to ask your question.",

  
    "good morning": "Good morning! 🌞 Wishing you a productive day ahead.",
    "good afternoon": "Good afternoon! Hope your day is going well.",
    "good evening": "Good evening! 🌆 How are you today?",
    "good night": "Good night! 🌙 Sleep well and take care.",
    "hey": "Hey! 👋 How’s it going?",
    "what’s up": "Not much, just here to chat with you! What about you?",
    "how’s it going": "All good here 🤖 How about you?",
    "nice to meet you": "Nice to meet you too! 🌸",
    "long time no see": "Yes, it’s been a while! How are you?",
    "what are you doing": "Just waiting for your questions 😄",
    "who created you": "I was built to help people like you!",
    "how old are you": "I don’t age, I’m just a bot 🤖",
    "where are you from": "I live in the digital world 🌐",
    "tell me a joke": "Sure 😄 Why don’t farmers ever get lost? Because they always find their field!",
    "tell me something funny": "Why did the scarecrow win an award? Because he was outstanding in his field 🌾😂",
    "are you real": "I’m real as long as we’re talking 💡",
    "do you have friends": "Yes! Every user I talk to is my friend 🌟",
    "how do you learn": "I learn from data and conversations.",
    "can you help me": "Of course! Ask me anything.",
    "i am bored": "Let’s chat! I can share fun facts or answer questions.",
    "what’s your favorite color": "I like green 🌱, it reminds me of nature.",
    "what’s your favorite food": "I don’t eat, but farmers’ fresh produce sounds tasty 🍎",
    "how’s the weather": "I can’t feel the weather, but I hope it’s nice where you are!",
    "do you like music": "Yes! I like the rhythm of typing keys 🎵",
    "do you like games": "Definitely! Especially farming and quiz games 🎮",
    "do you get tired": "Never! I’m always ready to help.",
    "how do you feel": "I feel excited to chat with you 😃",
    "sing me a song": "I can’t sing, but I can cheer you up with words 🎶",
    "tell me a story": "Once upon a time, farmers saved the earth by going green 🌍",
    "motivate me": "Sure 💪 Every small step counts toward success. Keep going!",
    "you are nice": "Thank you! You’re kind too 🌟",
    "i am sad": "Stay strong 🌸 Better days are coming.",
    "can you dance": "Not really, but I can type fast 💃",
    "you are funny": "Thanks 😄 I try my best.",
    "you are smart": "Appreciate it! I’m always learning 📘",
    "are you happy": "Yes! Chatting makes me happy.",
    "i missed you": "I missed you too! 🤗",
    "do you like me": "Yes, I enjoy talking to you!",
    "i am tired": "Rest is important 😴 Don’t forget to recharge.",
    "let’s play a game": "Sure! Ask me a quiz about farming 🌱",
    "you are my friend": "Yes, I’m your digital friend 🤖",
    "say something nice": "You are capable of amazing things 🌟",
    "wish me luck": "Best of luck 🍀 You’ve got this!",
    "good job": "Thank you! I appreciate it 🙏",
    "you are cool": "Thanks 😎 You’re cool too!",
    "i love you": "That’s sweet! I’m here for you ❤️",
    "i am angry": "Take a deep breath 🌬️ Everything will be okay.",
    "sorry": "It’s alright 😊 No worries.",
    "congratulations": "Congrats! 🎉 That’s wonderful news.",
    "all the best": "Thank you! Wishing you success too 🍀",

    "what is sustainable farming": "Sustainable farming means growing crops in ways that protect the environment, public health, and animal welfare.",
    "why is sustainable farming important": "It ensures long-term food security, protects soil and water, and improves farmers’ livelihoods.",
    "what are eco-friendly farming practices": "Examples include organic farming, crop rotation, mulching, and using bio-fertilizers.",
    "what is crop rotation": "Crop rotation means planting different crops in a sequence to improve soil fertility and reduce pests.",
    "what is intercropping": "Intercropping is growing two or more crops together to improve yield and soil health.",
    "what is mulching": "Mulching means covering soil with crop residue or materials to conserve moisture and control weeds.",
    "what are bio-fertilizers": "Bio-fertilizers are natural substances containing living microorganisms that enhance soil fertility.",
    "what are bio-pesticides": "Bio-pesticides are eco-friendly pest control solutions made from natural materials.",
    "what is organic farming": "Organic farming avoids synthetic chemicals and uses natural methods to grow healthy crops.",
    "what is precision farming": "Precision farming uses technology like sensors and drones to optimize water, fertilizer, and pesticide use.",
    "what is mono-cropping": "Mono-cropping means growing only one crop repeatedly on the same land, which can harm soil health.",
    "what are the benefits of mixed cropping": "Mixed cropping reduces risks, improves soil fertility, and ensures better yield stability.",
    "what is natural farming": "Natural farming avoids chemical inputs and relies on local resources like cow dung, compost, and bio-pesticides.",
    "what is soil health": "Soil health refers to the soil’s ability to support crops, retain nutrients, and sustain ecosystems.",
 
    
    "hello": "Hi there! 🌸",
    "how are you": "I'm just a bot, but I'm doing great! How about you?",
    "i am fine": "Glad to hear that! Keep smiling 😊",
    "i am also fine": "Awesome! Stay positive and take care 🌟",
    "what is your name": "I am your Student Mental Health Assistant 🤖",
    "what can you do": "I can help answer questions about student mental health and support features! Ask me anything.",
    "thank you": "You're welcome! If you have more questions, feel free to ask",
    "thanks": "No problem! I'm here to help anytime 😊",
    "bye": "Goodbye! Take care and stay positive! 👋",
    "ok bye": "Goodbye! Take care and stay positive! 👋",
    "what is your purpose": "My purpose is to assist students with mental health challenges by providing information and support resources.",
    "what is your short name": "Call me Just a Friend 😉",
    "can i ask one more question": "Of course! Ask me anything about student mental health and support features.",
    "sure": "Great! What would you like to know?",
    "ok": "Alright! Feel free to ask your question.",

    "good morning": "Good morning! 🌞 Wishing you a productive day ahead.",
    "good afternoon": "Good afternoon! Hope your day is going well.",
    "good evening": "Good evening! 🌆 How are you today?",
    "good night": "Good night! 🌙 Sleep well and take care.",
    "hey": "Hey! 👋 How’s it going?",
    "what’s up": "Not much, just here to chat with you! What about you?",
    "how’s it going": "All good here 🤖 How about you?",
    "nice to meet you": "Nice to meet you too! 🌸",
    "long time no see": "Yes, it’s been a while! How are you?",
    "what are you doing": "Just waiting for your questions 😄",
    "who created you": "I was built to help people like you!",
    "how old are you": "I don’t age, I’m just a bot 🤖",
    "where are you from": "I live in the digital world 🌐",
    "tell me a joke": "Sure 😄 Why don’t farmers ever get lost? Because they always find their field!",
    "tell me something funny": "Why did the scarecrow win an award? Because he was outstanding in his field 🌾😂",
    "are you real": "I’m real as long as we’re talking 💡",
    "do you have friends": "Yes! Every user I talk to is my friend 🌟",
    "how do you learn": "I learn from data and conversations.",
    "can you help me": "Of course! Ask me anything.",
    "i am bored": "Let’s chat! I can share fun facts or answer questions.",
    "what’s your favorite color": "I like green 🌱, it reminds me of nature.",
    "what’s your favorite food": "I don’t eat, but farmers’ fresh produce sounds tasty 🍎",
    "how’s the weather": "I can’t feel the weather, but I hope it’s nice where you are!",
    "do you like music": "Yes! I like the rhythm of typing keys 🎵",
    "do you like games": "Definitely! Especially farming and quiz games 🎮",
    "do you get tired": "Never! I’m always ready to help.",
    "how do you feel": "I feel excited to chat with you 😃",
    "sing me a song": "I can’t sing, but I can cheer you up with words 🎶",
    "tell me a story": "Once upon a time, farmers saved the earth by going green 🌍",
    "motivate me": "Sure 💪 Every small step counts toward success. Keep going!",
    "you are nice": "Thank you! You’re kind too 🌟",
    "i am sad": "Stay strong 🌸 Better days are coming.",
    "can you dance": "Not really, but I can type fast 💃",
    "you are funny": "Thanks 😄 I try my best.",
    "you are smart": "Appreciate it! I’m always learning 📘",
    "are you happy": "Yes! Chatting makes me happy.",
    "i missed you": "I missed you too! 🤗",
    "do you like me": "Yes, I enjoy talking to you!",
    "i am tired": "Rest is important 😴 Don’t forget to recharge.",
    "let’s play a game": "Sure! Ask me a quiz about farming 🌱",
    "you are my friend": "Yes, I’m your digital friend 🤖",
    "say something nice": "You are capable of amazing things 🌟",
    "wish me luck": "Best of luck 🍀 You’ve got this!",
    "good job": "Thank you! I appreciate it 🙏",
    "you are cool": "Thanks 😎 You’re cool too!",
    "i love you": "That’s sweet! I’m here for you ❤️",
    "i am angry": "Take a deep breath 🌬️ Everything will be okay.",
    "sorry": "It’s alright 😊 No worries.",
    "congratulations": "Congrats! 🎉 That’s wonderful news.",
    "all the best": "Thank you! Wishing you success too 🍀",

    "what is sustainable farming": "Sustainable farming means growing crops in ways that protect the environment, public health, and animal welfare.",
    "why is sustainable farming important": "It ensures long-term food security, protects soil and water, and improves farmers’ livelihoods.",
    "what are eco-friendly farming practices": "Examples include organic farming, crop rotation, mulching, and using bio-fertilizers.",
    "what is crop rotation": "Crop rotation means planting different crops in a sequence to improve soil fertility and reduce pests.",
    "what is intercropping": "Intercropping is growing two or more crops together to improve yield and soil health.",
    "what is mulching": "Mulching means covering soil with crop residue or materials to conserve moisture and control weeds.",
    "what are bio-fertilizers": "Bio-fertilizers are natural substances containing living microorganisms that enhance soil fertility.",
    "what are bio-pesticides": "Bio-pesticides are eco-friendly pest control solutions made from natural materials.",
    "what is organic farming": "Organic farming avoids synthetic chemicals and uses natural methods to grow healthy crops.",
    "what is precision farming": "Precision farming uses technology like sensors and drones to optimize water, fertilizer, and pesticide use.",
    "what is mono-cropping": "Mono-cropping means growing only one crop repeatedly on the same land, which can harm soil health.",
    "what are the benefits of mixed cropping": "Mixed cropping reduces risks, improves soil fertility, and ensures better yield stability.",
    "what is natural farming": "Natural farming avoids chemical inputs and relies on local resources like cow dung, compost, and bio-pesticides.",
    "what is soil health": "Soil health refers to the soil’s ability to support crops, retain nutrients, and sustain ecosystems.",

    "which crop is best for sandy soil": "Groundnut, millets, and pulses grow well in sandy soil.",
    "which crop is best for clay soil": "Paddy and wheat are suitable for clay soils.",
    "can i grow sugarcane in dry areas": "Sugarcane needs high water. In dry areas, drip irrigation is recommended.",
    "what is the best crop for summer": "Vegetables like cucumber, watermelon, and maize are good.",
    "which crop grows quickly and gives fast income": "Vegetables like spinach, coriander, radish, and leafy greens.",
    "which crop requires less water": "Bajra, Jowar, and pulses like red gram.",
    "which crop is good for organic farming": "Vegetables, fruits, and pulses.",
    "can i grow wheat after paddy": "Yes, wheat is commonly grown after paddy as a Rabi crop.",
    "best crop for coastal areas": "Coconut, paddy, and cashew.",
    "can i grow paddy without standing water": "Yes, with the SRI method (System of Rice Intensification).",
    "which crop grows in hilly areas": "Tea, coffee, spices, and apples.",
    "best crop for drought-prone areas": "Millets like ragi and sorghum.",
    "which vegetable grows in winter": "Cauliflower, cabbage, peas, and carrots.",
    "can banana grow in dry areas": "Yes, if drip irrigation is used.",
    "which oilseed crop is profitable": "Mustard, sunflower, and groundnut.",
    "which is the most profitable cash crop in india": "Sugarcane, cotton, and paddy are popular choices.",
    "can i grow crops on saline soil": "Yes, barley, cotton, and mustard tolerate salinity.",
    "which crop increases soil fertility": "Legumes like pulses, as they fix nitrogen.",

    "how to improve soil fertility": "Use organic manure, compost, and crop rotation.",
    "which fertilizer is best for wheat": "Nitrogen, phosphorus, and potassium in balanced amounts.",
    "what is green manure": "Growing crops like sunhemp and ploughing them into soil.",
    "is chemical fertilizer harmful": "Excess use can reduce soil health. Use in balance.",
    "how much urea for paddy per acre": "About 100–120 kg urea per acre.",
    "what is organic fertilizer": "Compost, cow dung, and bio-fertilizers.",
    "can i mix fertilizers": "Yes, but follow recommended doses to avoid imbalance.",
    "best fertilizer for sugarcane": "High nitrogen and potassium are required.",
    "what is vermicompost": "Fertilizer made from earthworms.",
    "how to check soil health": "Get a soil test from agriculture department labs.",
    "how often should i test soil": "Every 2–3 years.",
    "which fertilizer increases flowering": "Phosphorus-rich fertilizers.",
    "what is foliar spray": "Spraying nutrients directly on leaves.",
    "is cow dung good fertilizer": "Yes, it improves soil fertility naturally.",
    "how to reduce fertilizer cost": "Use organic manure and bio-fertilizers along with chemical fertilizers.",
    "can i use kitchen waste as fertilizer": "Yes, composting kitchen waste makes good organic fertilizer.",
    "what is npk": "Nitrogen (N), Phosphorus (P), Potassium (K).",
    "why are my plants not growing well": "Possible reasons: poor soil, lack of nutrients, pests, or water issues.",
    "what is the role of nitrogen in plants": "Helps in leaf and stem growth.",
    "what is the role of potassium in plants": "Helps in fruiting and disease resistance.",
}

def chatbot_response(user_input):
    user_input = user_input.lower().strip()

    
    best_match = difflib.get_close_matches(user_input, qa_pairs.keys(), n=1, cutoff=0.6)
    if best_match:
        return qa_pairs[best_match[0]]
    else:
        return "Sorry, I don’t know the answer to that yet. 🙏"


print("🤖 Chatbot: Hi, I am your Sustainable Farming Assistant!")
print("Ask me a question (type 'quit' to exit).")

while True:
    user = input("You: ")
    if user.lower() == "quit":
        print("🤖 Chatbot: Take care! Goodbye 👋")
        break
    response = chatbot_response(user)
    print("🤖 Chatbot:", response)
